package stockkeeper.network;
public enum MessageType {
		CHESTCONTENTS,
		COUNT, INVITE, REGISTER, CHECKGROUP, FINDITEM, INVALID_PASSWORD, CONNECTION_FAILED, GROUPCHANGED, MAKEGROUP, INVITEGROUP, COUNTALL

	}